# GitHub Pages configuration
theme: null
plugins: []

# Exclude files from GitHub Pages build
exclude:
  - README.md
  - LICENSE
  - .gitignore
  - .github
  - Assets
  - NativePlugins
  - Packages
  - ProjectSettings
  - docs
  - "*.meta"