services:
  openjtalk-wasm-builder:
    build:
      context: .
      dockerfile: Dockerfile.wasm
    volumes:
      - ./output:/output
    command: |
      sh -c "
        ls -la /build/build_wasm/ &&
        ls -la /build/build_wasm/lib/ || true &&
        cp /build/build_wasm/openjtalk_wrapper.js /output/ || cp /build/build_wasm/lib/openjtalk_wrapper.js /output/ &&
        cp /build/build_wasm/openjtalk_wrapper.wasm /output/ || cp /build/build_wasm/lib/openjtalk_wrapper.wasm /output/ &&
        echo 'Build files copied to output directory'
      "