name: Build OpenJTalk Native Libraries

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'NativePlugins/OpenJTalk/**'
      - '.github/workflows/build-openjtalk-native.yml'
  pull_request:
    paths:
      - 'NativePlugins/OpenJTalk/**'
      - '.github/workflows/build-openjtalk-native.yml'
  workflow_dispatch:

jobs:
  build-windows:
    name: Build Windows (${{ matrix.arch }})
    runs-on: windows-latest
    timeout-minutes: 45  # Windowsビルドは時間がかかるため45分
    strategy:
      matrix:
        arch: [x64]
        include:
          - arch: x64
            cmake_arch: x64
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v1.1
    
    - name: Setup MSVC Environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
    
    - name: Setup Dependencies
      shell: cmd
      run: |
        cd NativePlugins\OpenJTalk
        echo Fetching and building OpenJTalk dependencies...
        if exist fetch_dependencies.bat (
          echo Using Windows batch script
          call fetch_dependencies.bat
        ) else (
          echo Using Git Bash for shell script
          "C:\Program Files\Git\bin\bash.exe" fetch_dependencies.sh
        )
        if exist build_dependencies_msvc.bat (
          echo Using MSVC build script
          call build_dependencies_msvc.bat
        ) else (
          echo Using Git Bash for build script
          "C:\Program Files\Git\bin\bash.exe" build_dependencies.sh
        )
    
    - name: Check Dictionary Files
      shell: bash
      run: |
        cd NativePlugins/OpenJTalk
        echo "Checking dictionary files..."
        ls -la dictionary/ || echo "Dictionary directory not found"
        # No need to download, dictionary is already in repo
    
    - name: Build Native Library
      shell: cmd
      run: |
        cd NativePlugins\OpenJTalk
        if exist build rmdir /s /q build
        mkdir build
        cd build
        echo Running CMake configuration...
        cmake --version
        cmake .. -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release
        echo Building project...
        nmake
        echo Build completed successfully
        dir /s *.dll
    
    - name: Run Tests
      shell: bash
      run: |
        cd NativePlugins/OpenJTalk/build
        echo "Running tests..."
        ctest -C Release --output-on-failure -V || {
          echo "Test failed with error code $?"
          exit 0
        }
    
    - name: Prepare Artifacts
      shell: bash
      run: |
        mkdir -p artifacts/windows/${{ matrix.arch }}
        # Find and copy DLL from build output
        find NativePlugins/OpenJTalk/build -name "*.dll" -type f | head -5
        cp NativePlugins/OpenJTalk/build/bin/Release/*.dll artifacts/windows/${{ matrix.arch }}/ 2>/dev/null || \
        cp NativePlugins/OpenJTalk/build/Release/*.dll artifacts/windows/${{ matrix.arch }}/ 2>/dev/null || \
        cp NativePlugins/OpenJTalk/build/bin/*.dll artifacts/windows/${{ matrix.arch }}/ 2>/dev/null || true
        # Copy header files
        cp NativePlugins/OpenJTalk/include/*.h artifacts/ || true
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: openjtalk-windows-${{ matrix.arch }}
        path: artifacts/

  build-linux:
    name: Build Linux (${{ matrix.arch }})
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        arch: [x86_64]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
    
    - name: Setup Dependencies
      run: |
        cd NativePlugins/OpenJTalk
        echo "Fetching and building OpenJTalk dependencies..."
        # Use CI-specific scripts for better reliability
        if [ -f "fetch_dependencies_ci.sh" ]; then
          chmod +x fetch_dependencies_ci.sh build_dependencies_ci.sh
          ./fetch_dependencies_ci.sh
          ./build_dependencies_ci.sh
        else
          chmod +x fetch_dependencies.sh build_dependencies.sh
          ./fetch_dependencies.sh
          ./build_dependencies.sh
        fi
    
    - name: Setup Cross Compilation (aarch64)
      if: matrix.arch == 'aarch64'
      run: |
        sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
        echo "CC=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
        echo "CXX=aarch64-linux-gnu-g++" >> $GITHUB_ENV
    
    - name: Check Dictionary Files
      run: |
        cd NativePlugins/OpenJTalk
        echo "Checking dictionary files..."
        ls -la dictionary/ || echo "Dictionary directory not found"
    
    - name: Configure CMake
      run: |
        cd NativePlugins/OpenJTalk
        mkdir -p build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
    
    - name: Build
      run: |
        cd NativePlugins/OpenJTalk/build
        make -j$(nproc)
    
    - name: Run Tests (x86_64 only)
      if: matrix.arch == 'x86_64'
      run: |
        cd NativePlugins/OpenJTalk/build
        # Run all tests using CTest
        ctest --output-on-failure
    
    - name: Prepare Artifacts
      run: |
        mkdir -p artifacts/linux/${{ matrix.arch }}
        # Copy shared library from build output
        cp NativePlugins/OpenJTalk/build/lib/*.so artifacts/linux/${{ matrix.arch }}/ || true
        # Copy header files
        cp NativePlugins/OpenJTalk/include/*.h artifacts/ || true
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: openjtalk-linux-${{ matrix.arch }}
        path: artifacts/

  build-macos:
    name: Build macOS
    runs-on: macos-latest
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install CMake
      run: brew install cmake
    
    - name: Setup Dependencies
      run: |
        cd NativePlugins/OpenJTalk
        echo "Fetching and building OpenJTalk dependencies..."
        # Use CI-specific scripts for better reliability
        if [ -f "fetch_dependencies_ci.sh" ]; then
          chmod +x fetch_dependencies_ci.sh build_dependencies_ci.sh
          ./fetch_dependencies_ci.sh
          ./build_dependencies_ci.sh
        else
          chmod +x fetch_dependencies.sh build_dependencies.sh
          ./fetch_dependencies.sh
          ./build_dependencies.sh
        fi
    
    - name: Check Dictionary Files
      run: |
        cd NativePlugins/OpenJTalk
        echo "Checking dictionary files..."
        ls -la dictionary/ || echo "Dictionary directory not found"
    
    - name: Build Native Library
      run: |
        cd NativePlugins/OpenJTalk
        mkdir -p build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make -j$(sysctl -n hw.ncpu)
    
    - name: Run Tests
      run: |
        cd NativePlugins/OpenJTalk/build
        # Run all tests using CTest
        ctest --output-on-failure
    
    - name: Prepare Artifacts
      run: |
        mkdir -p artifacts/macos
        # Copy the dylib
        cp NativePlugins/OpenJTalk/build/lib/libopenjtalk_wrapper.dylib artifacts/macos/
        # Copy header files
        cp NativePlugins/OpenJTalk/include/*.h artifacts/ || true
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: openjtalk-macos-universal
        path: artifacts/


  create-release:
    name: Create Release Package
    needs: [build-windows, build-linux, build-macos]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download All Artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts/
    
    - name: Create Unity Plugin Structure
      run: |
        mkdir -p uPiper-OpenJTalk-Native/Plugins/Windows/x86_64
        mkdir -p uPiper-OpenJTalk-Native/Plugins/Linux/x86_64
        mkdir -p uPiper-OpenJTalk-Native/Plugins/Linux/aarch64
        mkdir -p uPiper-OpenJTalk-Native/Plugins/macOS
        mkdir -p uPiper-OpenJTalk-Native/Include
        
        # Windows
        cp artifacts/openjtalk-windows-x64/windows/x64/*.dll uPiper-OpenJTalk-Native/Plugins/Windows/x86_64/
        
        # Linux
        cp artifacts/openjtalk-linux-x86_64/linux/x86_64/*.so uPiper-OpenJTalk-Native/Plugins/Linux/x86_64/
        cp artifacts/openjtalk-linux-aarch64/linux/aarch64/*.so uPiper-OpenJTalk-Native/Plugins/Linux/aarch64/
        
        # macOS
        cp artifacts/openjtalk-macos-universal/macos/*.dylib uPiper-OpenJTalk-Native/Plugins/macOS/
        
        # Headers
        cp artifacts/openjtalk-windows-x64/*.h uPiper-OpenJTalk-Native/Include/
        
        # Create README
        cat > uPiper-OpenJTalk-Native/README.md << EOF
        # uPiper OpenJTalk Native Libraries
        
        This package contains pre-built OpenJTalk native libraries for Unity.
        
        ## Supported Platforms
        - Windows (x64 only)
        - Linux (x86_64, aarch64)
        - macOS (Universal Binary: x86_64 + arm64)
        
        ## Installation
        1. Copy the contents of the Plugins folder to your Unity project's Assets/Plugins folder
        2. Include the header files from the Include folder in your native code if needed
        
        ## Version
        Built from commit: ${{ github.sha }}
        Build date: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
        EOF
    
    - name: Create Archive
      run: |
        zip -r uPiper-OpenJTalk-Native.zip uPiper-OpenJTalk-Native/
    
    - name: Upload Release Package
      uses: actions/upload-artifact@v4
      with:
        name: uPiper-OpenJTalk-Native-Release
        path: uPiper-OpenJTalk-Native.zip