name: .NET Format Check

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.cs'
      - '**.csproj'
      - '.editorconfig'
      - '.github/workflows/dotnet-format.yml'

jobs:
  check-format:
    runs-on: ubuntu-latest
    name: Check C# Format
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6.0.x
          7.0.x
          8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Install dotnet format
      run: dotnet tool install -g dotnet-format || true

    - name: Check format
      run: |
        export PATH="$PATH:$HOME/.dotnet/tools"
        dotnet format --verify-no-changes --verbosity diagnostic