name: Unity IL2CPP Native Runners (Experimental)

on:
  workflow_dispatch:
    inputs:
      enableWindows:
        description: 'Enable Windows IL2CPP build'
        required: false
        default: 'false'
        type: boolean
      enableMacOS:
        description: 'Enable macOS IL2CPP build'
        required: false
        default: 'false'
        type: boolean

jobs:
  # Windows IL2CPP on Windows Runner
  build-windows-il2cpp:
    name: Windows IL2CPP (Native)
    runs-on: windows-latest
    if: github.event.inputs.enableWindows == 'true'
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
        
    - name: Setup Unity
      uses: Unity-Technologies/setup-unity@v1
      with:
        unity-version: 6000.0.35f1
        unity-modules: windows-il2cpp
        
    - name: Activate Unity License
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      run: |
        "${env:UNITY_PATH}/Unity.exe" -batchmode -quit -nographics `
          -username "${env:UNITY_EMAIL}" `
          -password "${env:UNITY_PASSWORD}" `
          -serial "${env:UNITY_LICENSE}"
        
    - name: Build IL2CPP
      run: |
        "${env:UNITY_PATH}/Unity.exe" -batchmode -quit -nographics `
          -projectPath . `
          -buildTarget Win64 `
          -executeMethod UnityBuilderAction.BuildScript.Build `
          -customBuildPath build/StandaloneWindows64 `
          -customBuildName uPiper `
          -scriptingBackend IL2CPP `
          -logFile build.log
          
    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: Windows-IL2CPP-Native
        path: build/StandaloneWindows64
        retention-days: 7

  # macOS IL2CPP on macOS Runner  
  build-macos-il2cpp:
    name: macOS IL2CPP (Native)
    runs-on: macos-latest
    if: github.event.inputs.enableMacOS == 'true'
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
        
    - name: Setup Unity
      uses: Unity-Technologies/setup-unity@v1
      with:
        unity-version: 6000.0.35f1
        unity-modules: mac-il2cpp
        
    - name: Activate Unity License
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      run: |
        /Applications/Unity/Unity.app/Contents/MacOS/Unity -batchmode -quit -nographics \
          -username "$UNITY_EMAIL" \
          -password "$UNITY_PASSWORD" \
          -serial "$UNITY_LICENSE"
        
    - name: Build IL2CPP
      run: |
        /Applications/Unity/Unity.app/Contents/MacOS/Unity -batchmode -quit -nographics \
          -projectPath . \
          -buildTarget StandaloneOSX \
          -executeMethod UnityBuilderAction.BuildScript.Build \
          -customBuildPath build/StandaloneOSX \
          -customBuildName uPiper \
          -scriptingBackend IL2CPP \
          -logFile build.log
          
    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: macOS-IL2CPP-Native
        path: build/StandaloneOSX
        retention-days: 7

  # Alternative: Self-hosted runner example
  build-self-hosted:
    name: IL2CPP on Self-Hosted Runner
    runs-on: [self-hosted, "${{ matrix.platform }}"]
    if: false  # Disabled by default - enable if you have self-hosted runners
    strategy:
      matrix:
        include:
          - platform: windows
            target: StandaloneWindows64
          - platform: macos
            target: StandaloneOSX
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
        
    - name: Build with IL2CPP
      run: |
        # Assumes Unity is pre-installed on self-hosted runner
        unity -batchmode -quit -nographics \
          -projectPath . \
          -buildTarget ${{ matrix.target }} \
          -executeMethod UnityBuilderAction.BuildScript.Build \
          -customBuildPath build/${{ matrix.target }} \
          -customBuildName uPiper \
          -scriptingBackend IL2CPP
          
    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.platform }}-IL2CPP-SelfHosted
        path: build/${{ matrix.target }}
        retention-days: 7